### ISSUE TITLE
Some components are not found

### ISSUE THREAD

**Issue by sobolevn** [kartojal/testcafe-nuxt-selectors#1]
Hi, thanks for this fork!

I have tried to used this library with this setup.
Base template: https://github.com/wemake-services/wemake-vue-template

`testcafe.js`:

```js
import NuxtSelector from './testcafe-nuxt'

fixture('Getting Started')
  .page('http://localhost:3000')
  .beforeEach(async () => await NuxtSelector())

test('uses correct layout', async (t) => {
  const root = NuxtSelector()
  const rootVue = await root.getVue()

  await t.expect(root.exists).ok()
  await t.expect(rootVue.state.layoutName).eql('default')
})

test('all Comments are present', async (t) => {
  const comments = NuxtSelector('Comment')

  await t.expect(comments.count).eql(10)
})
```

Running: `nuxt build && testcafe chrome --app \"yarn start\" --app-init-delay 10000 testcafe.js`

## What happened

For some reason while doing it I was unable to find any `Comment` components.
I have forked your plugin to play around with it. I have found a problem inside this function:

```js
function getComponentTag (instance) {
            return (
        instance.$options.name ||
        instance.$options._componentTag ||
        instance.$options.__file ||
        ''
            );
}
```

Because `instance.$options.name` was always set to `'e'`. And `instance.$options._componentTag` had the desired `'comment'` name.

## Solution

As a result I have tweaked this function to work like so:

```js
    function getComponentTags (instance) {
      const candidates = [
        instance.$options.name,
        instance.$options._componentTag,
        instance.$options.__file
      ]

      return candidates.filter((e) => e) // filter out false values
    }

// ...
// Here's how I am calling it:
walkVueComponentNodes(root, 0, (node, tagIndex) => {
  return getComponentTags(node).indexOf(tags[tagIndex]) !== -1
})
```

And now it is working. @kartojal does it look good to you?
May I send a PR with this fix?

Related: https://github.com/wemake-services/wemake-vue-template/issues/504

**Comment by kartojal** [comment]
Of course, any improvements are welcome, will wait the PR. :+1:
